version: '3.9'

x-common-env: &common-env
    REDIS_HOST: "redis"

networks:
    external:
        driver: bridge
    internal:
        driver: bridge

services:
    nginx:
        image: nginx:alpine
        networks:
            - external
            - internal
        restart: always
        ports:
            - "80:8080"
            - "443:8443"
            - "2096:2096"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./docker/nginx/ssl:/etc/nginx/ssl:ro
            - ./docker/nginx/logs:/var/log/nginx
        depends_on:
            - app
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
    redis:
        image: redis:alpine
        networks:
            - internal
            - external
        restart: always
        command: redis-server
        ports:
            - "6379:6379"
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
    websocket-server:
        image: quay.io/soketi/soketi:1.4-16-debian
        networks:
            - internal
            - external
        restart: always
#        volumes:
#            -   source: ./docker/certs
#                target: /certs
#                type: bind
        environment:
            SOKETI_METRICS_SERVER_PORT: '9601'
            SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES: 'true'
            SOKETI_DB_REDIS_HOST: 'redis'
#            SOKETI_SSL_CERT: '/certs/tls.crt'
#            SOKETI_SSL_KEY: '/certs/tls.key'
    #        ports:
    #            - '${SOKETI_PORT:-6001}:6001'
    #            - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - redis
            - websocket-server
            - nginx
        networks:
            - internal
            - external
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        ports:
            - '5173:5173'
            - '49200:49200'
        environment: *common-env
        image: ghcr.io/prophet731/network-looking-glass
        volumes:
            - source: ./
              target: /var/www/
              type: bind
            - source: ./docker/certs
              target: /certs
              type: bind
