version: '3.9'

x-common-env: &common-env
    REDIS_HOST: "redis"

networks:
    lg:
        driver: bridge

services:
    redis:
        image: redis:alpine
        networks:
            - lg
        restart: always
        command: redis-server
        ports:
            - "6379:6379"
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
    websocket-server:
        image: quay.io/soketi/soketi:1.4-16-debian
        networks:
            - lg
        restart: always
        environment:
            SOKETI_METRICS_SERVER_PORT: '9601'
            SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES: 'true'
        ports:
            - '${SOKETI_PORT:-6001}:6001'
            - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - redis
            - websocket-server
        networks:
            - lg
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        ports:
            - '80:8081'
            - '5173:5173'
            - '49200:49200'
        environment: *common-env
        image: ghcr.io/prophet731/network-looking-glass
        volumes:
            - ./:/var/www:rw
